FROM agencybench-sandbox

LABEL query="en_sleep_screen_stats"
LABEL task="Statistical Analysis of Sleep and Screen Time"

RUN pip3 install --no-cache-dir \
    scipy \
    seaborn

WORKDIR /agencybench
CMD []
